### ISSUE TITLE
在vue项目中，安装按安装包运行直接报错

### ISSUE THREAD

**Issue by yanghaijun** [hehu158/jiaminghi-data-view-datav-for-vite2-vue3#1]
node_modules/@jiaminghi/data-view/lib/components/decoration3/src/main.vue 
  7  |        >
  8  |          <rect
  9  |            :key="i"
     |             ^
  10 |            :fill="mergedColor[0]"
  11 |            :x="point[0] - halfPointSideLength"

**Comment by hehu158** [comment]
下载了csdn的补丁不行？

**Comment by hehu158** [comment]
> node_modules/@jiaminghi/data-view/lib/components/decoration3/src/main.vue 7 | > 8 | <rect 9 | :key="i" | ^ 10 | :fill="mergedColor[0]" 11 | :x="point[0] - halfPointSideLength"
如果是csdn下载的补丁不行，请在csdn上联系我，安装好补丁一般都没啥问题的，下载前看清楚是npm/yarn、cnpm或pnpm就行。
